title: "Farhan's Corner"
author: "Farhan Wali"
description: "Reflections on my fascinations"
mathjax: true

pages_list:
  About: "/about.md"
  Archive: "/archive.md"

links:
  - github: "https://github.com/FarhanWaldo"

theme: jekyll-theme-tactile