title: "Farhan's Corner"
author: "Farhan Wali"
description: "Reflections on my fascinations"
mathjax: true

pages_list:
  About: '/about'
  Archive: '/archive'

links:
  - github: "https://github.com/FarhanWaldo"

theme: jekyll-theme-tactile